name: test
on: [push, pull_request]

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.18.x, 1.20.x]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v4
      - name: Test
        run: go test -v ./...
